### ISSUE TITLE
Fails to install on Debian testing

### ISSUE THREAD

**Issue by RalfJung** [volschin/node-curve25519#16]
I am trying to build Signal-Desktop on Debian testing, and (I think) this package fails to build (but I know next to nothing about npm so if my analysis is wrong here please tell me):
```
error /home/r/src/android/Signal-Desktop/node_modules/curve25519-n: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/r/src/android/Signal-Desktop/node_modules/curve25519-n
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@12.13.1 | linux | x64
gyp info find Python using Python version 2.7.18 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [
gyp info spawn args   '/usr/share/nodejs/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/r/src/android/Signal-Desktop/node_modules/curve25519-n/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/share/nodejs/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/include/nodejs/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/usr/include/nodejs',
gyp info spawn args   '-Dnode_gyp_dir=/usr/share/nodejs/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/usr/include/nodejs/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/r/src/android/Signal-Desktop/node_modules/curve25519-n',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Traceback (most recent call last):
  File "/usr/share/nodejs/node-gyp/gyp/gyp_main.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'gyp==0.1' distribution was not found and is required by the application
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/nodejs/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.6.13
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/r/src/android/Signal-Desktop/node_modules/curve25519-n
```
My guess is that the problem has to do with something here using legacy Python 2. I have the "gyp"  and "node-gyp" packages installed, but "gyp" depends on "python3-pkg-resources" and I had to install the Python 2 version python-pkg-resources to even get this far (I got a different error message before).

Is there anything I can do to still build Signal-Desktop? Which component needs to be updated to stop using an unsupported old Python version?

**Comment by RalfJung** [comment]
This is probably actually a bug in Debian's node-gyp: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962469
